name: servicesphereagent
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  google_fonts: ^6.3.3
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_rating_bar: ^4.0.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.1.0

# --- MAIN FLUTTER CONFIG ---
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/icon.png

# --- LAUNCHER ICON CONFIG ---
# Remove 'lib/' from these paths
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
