name: servicesphere
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0" # Use a standard SDK range

# --- APPLICATION DEPENDENCIES ---
# These are the packages your final app needs to run.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_rating_bar: ^4.0.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/icon.png"
  # adaptive_icon_background: "#FFFFFF"
